POST https://node-do-zero-b9lg.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Esse é o quarto vídeo",
    "duration": 180
}

###

GET https://node-do-zero-b9lg.onrender.com/videos

###

PUT https://node-do-zero-b9lg.onrender.com/videos/8ac366fd-ae35-47a8-8faf-9702d7b3976d
Content-Type: application/json

{
    "title": "Video 05",
    "description": "Esse é o quinto vídeo",
    "duration": 190
}

###

DELETE https://node-do-zero-b9lg.onrender.com/videos/737cf627-8a79-4ff2-804a-429ef87cad91
